version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_APM_SERVICEMAPENABLED= "true"
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY= aaaaaaaa-c4d3-4a0a-8290-2abcb83ab3aa
    volumes:
      - ./certs:/usr/share/kibana/config/certs
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.1
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./certs:/usr/share/logstash/config/certs
    ports:
      - "5001:5001"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

  springboot:
    build: .
    container_name: springboot
    ports:
      - "8080:8080"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash

networks:
  elk:

volumes:
  esdata:
